fix fio test disk full issue

diff --git a/.github/workflows/fio_benchmark.yml b/.github/workflows/fio_benchmark.yml
--- a/.github/workflows/fio_benchmark.yml
+++ b/.github/workflows/fio_benchmark.yml
@@ -96,12 +96,14 @@ jobs:
               fio_arg=$(echo $job | awk -F: '{print $2}' | xargs)
               mount_arg=$(echo $job | awk -F: '{print $3}' | xargs)
               minio_url=http://172.27.0.2:9005/$name
-              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s" "myminio/$name" "$?"
+              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s\n" "myminio/$name" "$?"
               while true; do
                 used=$(df -h /mnt/minio/data1  | awk 'NR>1 {gsub(/%/,""); print $5}') 
                 if [ used > $max_used ]; then
                   echo "sleep 10s"
                   sleep 10s
+                else
+                  break
                 fi
               done
               ./juicefs format --trash-days 0 --storage minio --bucket  $minio_url --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  ${{ steps.vars.outputs.META_URL }} fio-benchmark
