fix fio test disk full issue

diff --git a/.github/workflows/fio_benchmark.yml b/.github/workflows/fio_benchmark.yml
--- a/.github/workflows/fio_benchmark.yml
+++ b/.github/workflows/fio_benchmark.yml
@@ -19,7 +19,6 @@ jobs:
         id: vars
         run: |
           echo ::set-output name=META_URL::redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/6
-          echo ::set-output name=MINIO_URL::http://172.27.0.2:9005/juicefs-fio-benchmark
           echo ::set-output name=MOUNT_POINT::/tmp/juicefs-fio-benchmark
 
       - name: Build linux target
@@ -38,15 +37,14 @@ jobs:
           if [ -n "$UUID" ];then
             sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
           fi
-          bucket_name=$(basename ${{ steps.vars.outputs.MINIO_URL}})
-          mc rb  myminio/$bucket_name --force --dangerous || true
 
       - name: Fio Benchmark 
         run: |
           csv_file=/var/lib/mysql-files/result.csv
           juicefs_version=$(./juicefs -V|cut -b 17-)
           echo bandwidth, created_date, github_revision, workflow_url, juicefs_version, name, ref_name > $csv_file
-          default_size=1G
+          default_size=256M
+          max_used=10
           fio_jobs=(
             "big-file-sequential-read:      --rw=read --refill_buffers --bs=256k --size=${default_size}" \
             "big-file-sequential-write:     --rw=write --refill_buffers --bs=256k --size=${default_size}" \
@@ -94,10 +92,19 @@ jobs:
           do
             echo job is:, $job
             if [ -n "$job" ]; then
-              ./juicefs format --storage minio --bucket  ${{ steps.vars.outputs.MINIO_URL }} --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  ${{ steps.vars.outputs.META_URL }} fio-benchmark
               name=$(echo $job | awk -F: '{print $1}' | xargs)
               fio_arg=$(echo $job | awk -F: '{print $2}' | xargs)
               mount_arg=$(echo $job | awk -F: '{print $3}' | xargs)
+              minio_url=http://172.27.0.2:9005/$name
+              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s" "myminio/$name" "$?"
+              while true; do
+                used=$(df -h /mnt/minio/data1  | awk 'NR>1 {gsub(/G/,""); print $4}') 
+                if [ used > $max_used ]; then
+                  echo "sleep 10s"
+                  sleep 10s
+                fi
+              done
+              ./juicefs format --trash-days 0 --storage minio --bucket  $minio_url --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  ${{ steps.vars.outputs.META_URL }} fio-benchmark
               ./juicefs mount -d ${{ steps.vars.outputs.META_URL }} ${{ steps.vars.outputs.MOUNT_POINT }} --no-usage-report $mount_arg &
               if [[ "$name" =~ ^big-file-rand-read.* ]]; then
                 block_size=$(echo $name | awk -F- '{print $NF}' | xargs)
@@ -109,13 +116,12 @@ jobs:
               bw=$(tail -1 result.log | awk '{print $2}' | awk -F '=' '{print $2}' | cut -b 1,-3)
               echo $bw, $(date +"%Y-%m-%d %H:%M:%S"), ${{github.sha}}, https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}, $juicefs_version, $name, ${{ github.ref_name }} | tee -a $csv_file
               
-              ./juicefs umount ${{ steps.vars.outputs.MOUNT_POINT }}
+              ./juicefs umount -f ${{ steps.vars.outputs.MOUNT_POINT }}
               UUID=$(./juicefs status ${{ steps.vars.outputs.META_URL }} | grep UUID | cut -d '"' -f 4)
               if [ -n "$UUID" ];then
                 sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
               fi
-              bucket_name=$(basename ${{ steps.vars.outputs.MINIO_URL}})
-              mc rb  myminio/$bucket_name --force --dangerous || true
+              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s" "myminio/$name" "$?"
             fi
           done
           mysql -h 172.27.0.1 -u root -p${{secrets.MYSQL_PASSWORD}} -e "use  test_result; LOAD DATA INFILE '/var/lib/mysql-files/result.csv' INTO TABLE fio_test FIELDS TERMINATED BY ',' IGNORE 1 ROWS;" 
@@ -129,8 +135,6 @@ jobs:
           if [ -n "$UUID" ];then
             sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
           fi
-          bucket_name=$(basename ${{ steps.vars.outputs.MINIO_URL}})
-          mc rb  myminio/$bucket_name --force --dangerous || true
 
       - name: Send Slack Notification
         if: ${{ failure() }}
