fio using different version

diff --git a/.github/workflows/fio_benchmark.yml b/.github/workflows/fio_benchmark.yml
--- a/.github/workflows/fio_benchmark.yml
+++ b/.github/workflows/fio_benchmark.yml
@@ -20,6 +20,7 @@ jobs:
         run: |
           echo ::set-output name=META_URL::redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/6
           echo ::set-output name=MOUNT_POINT::/tmp/juicefs-fio-benchmark
+          echo ::set-output name=BACKWARD_VERSIONS::1
 
       - name: Build linux target
         run: |
@@ -41,10 +42,9 @@ jobs:
       - name: Fio Benchmark 
         run: |
           csv_file=/var/lib/mysql-files/result.csv
-          juicefs_version=$(./juicefs -V|cut -b 17-)
           echo bandwidth, created_date, github_revision, workflow_url, juicefs_version, name, ref_name > $csv_file
-          default_size=256M
-          warning_value=10
+          default_size=128M
+          warning_value=90
           fio_jobs=(
             "big-file-sequential-read:      --rw=read --refill_buffers --bs=256k --size=${default_size}" \
             "big-file-sequential-write:     --rw=write --refill_buffers --bs=256k --size=${default_size}" \
@@ -87,44 +87,56 @@ jobs:
             "small-file-multi-write-8:      --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=1000 --numjobs=8" \
             "small-file-multi-write-16:     --rw=write --file_service_type=sequential --bs=4k --filesize=4k --nrfiles=1000 --numjobs=16" \
           )
-
-          for job in "${fio_jobs[@]}"
-          do
-            echo job is:, $job
-            if [ -n "$job" ]; then
-              name=$(echo $job | awk -F: '{print $1}' | xargs)
-              fio_arg=$(echo $job | awk -F: '{print $2}' | xargs)
-              mount_arg=$(echo $job | awk -F: '{print $3}' | xargs)
-              minio_url=http://172.27.0.2:9005/$name
-              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s\n" "myminio/$name" "$?"
-              while true; do
-                used=$(df -h /mnt/minio/data1  | awk 'NR>1 {gsub(/%/,""); print $5}') 
-                if [ $used -gt $warning_value ]; then
-                  printf "disk used %s%%, sleep 10s\n" "$used"
-                  sleep 10s
-                else
-                  break
-                fi
-              done
-              ./juicefs format --trash-days 0 --storage minio --bucket  $minio_url --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  ${{ steps.vars.outputs.META_URL }} fio-benchmark
-              ./juicefs mount -d ${{ steps.vars.outputs.META_URL }} ${{ steps.vars.outputs.MOUNT_POINT }} --no-usage-report $mount_arg &
-              if [[ "$name" =~ ^big-file-rand-read.* ]]; then
-                block_size=$(echo $name | awk -F- '{print $NF}' | xargs)
-                echo block_size is $block_size
-                fio --name=big-file-rand-read-preload --directory=${{ steps.vars.outputs.MOUNT_POINT }} --rw=randread --refill_buffers --size=${default_size} --filename=randread.bin --bs=$block_size --pre_read=1
-                sudo sync && echo 3 > /proc/sys/vm/drop_caches
-              fi
-              fio --name=$name --directory=${{ steps.vars.outputs.MOUNT_POINT }} $fio_arg > result.log
-              bw=$(tail -1 result.log | awk '{print $2}' | awk -F '=' '{print $2}' | cut -b 1,-3)
-              echo $bw, $(date +"%Y-%m-%d %H:%M:%S"), ${{github.sha}}, https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}, $juicefs_version, $name, ${{ github.ref_name }} | tee -a $csv_file
-              
-              ./juicefs umount -f ${{ steps.vars.outputs.MOUNT_POINT }}
-              UUID=$(./juicefs status ${{ steps.vars.outputs.META_URL }} | grep UUID | cut -d '"' -f 4)
-              if [ -n "$UUID" ];then
-                sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
-              fi
-              mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s" "myminio/$name" "$?"
+          urls=("juicefs")
+          urls+=($(curl -s https://api.github.com/repos/juicedata/juicefs/releases | grep browser_download_url | grep linux-amd64.tar.gz | awk -F\" '{print $4}' | head -${{ steps.vars.outputs.BACKWARD_VERSIONS }}))          
+          for url in "${urls[@]}"; do
+            if [ url == http* ]; then  
+              rm juicefs 
+              echo download url is: $url
+              wget -q $url
+              tar -zxf $(basename $url)
+              rm $(basename $url)
             fi
+            juicefs_version=$(./juicefs -V|cut -b 17-)
+            echo juicefs version: $(./juicefs -V)
+            for job in "${fio_jobs[@]}"
+            do
+              echo job is:, $job
+              if [ -n "$job" ]; then
+                name=$(echo $job | awk -F: '{print $1}' | xargs)
+                fio_arg=$(echo $job | awk -F: '{print $2}' | xargs)
+                mount_arg=$(echo $job | awk -F: '{print $3}' | xargs)
+                minio_url=http://172.27.0.2:9005/$name
+                mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s\n" "myminio/$name" "$?"
+                while true; do
+                  used=$(df -h /mnt/minio/data1  | awk 'NR>1 {gsub(/%/,""); print $5}') 
+                  if [ $used -gt $warning_value ]; then
+                    printf "disk used %s%%, sleep 10s\n" "$used"
+                    sleep 10s
+                  else
+                    break
+                  fi
+                done
+                ./juicefs format --trash-days 0 --storage minio --bucket  $minio_url --access-key minioadmin --secret-key ${{ secrets.MINIO_SECRET_KEY }}  ${{ steps.vars.outputs.META_URL }} fio-benchmark
+                ./juicefs mount -d ${{ steps.vars.outputs.META_URL }} ${{ steps.vars.outputs.MOUNT_POINT }} --no-usage-report $mount_arg &
+                if [[ "$name" =~ ^big-file-rand-read.* ]]; then
+                  block_size=$(echo $name | awk -F- '{print $NF}' | xargs)
+                  echo block_size is $block_size
+                  fio --name=big-file-rand-read-preload --directory=${{ steps.vars.outputs.MOUNT_POINT }} --rw=randread --refill_buffers --size=${default_size} --filename=randread.bin --bs=$block_size --pre_read=1
+                  sudo sync && echo 3 > /proc/sys/vm/drop_caches
+                fi
+                fio --name=$name --directory=${{ steps.vars.outputs.MOUNT_POINT }} $fio_arg > result.log
+                bw=$(tail -1 result.log | awk '{print $2}' | awk -F '=' '{print $2}' | cut -b 1,-3)
+                echo $bw, $(date +"%Y-%m-%d %H:%M:%S"), ${{github.sha}}, https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}, $juicefs_version, $name, ${{ github.ref_name }} | tee -a $csv_file
+                
+                ./juicefs umount -f ${{ steps.vars.outputs.MOUNT_POINT }}
+                UUID=$(./juicefs status ${{ steps.vars.outputs.META_URL }} | grep UUID | cut -d '"' -f 4)
+                if [ -n "$UUID" ];then
+                  sudo ./juicefs destroy --force ${{ steps.vars.outputs.META_URL }} $UUID
+                fi
+                mc rb  myminio/$name --force --dangerous || printf "Warining; remove bucket failed: %s, exit code: %s" "myminio/$name" "$?"
+              fi
+            done
           done
           mysql -h 172.27.0.1 -u root -p${{secrets.MYSQL_PASSWORD}} -e "use  test_result; LOAD DATA INFILE '/var/lib/mysql-files/result.csv' INTO TABLE fio_test FIELDS TERMINATED BY ',' IGNORE 1 ROWS;" 
 
